[package]
name = "icorb"
version = "0.1.0"
edition = "2021"
description = "Core bussines logic of Interceptor Orbit"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
